language:
  - swift
osx_image: xcode10.1
script:
  - xcodebuild clean build test -project CLDVideoView.xcodeproj -scheme "travisScheme" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build test